"""CareerHub AI Utilities Package"""

from .models import (
    UserProfile,
    Experience,
    Education,
    Project,
)
from .skill_normalizer import (
    SkillNormalizer,
    normalize_skills,
)
from .supabase_client import (
    is_supabase_configured,
    get_supabase_client,
    sign_in_user,
    sign_up_user,
    sign_out_user,
    save_profile_to_db,
    load_profile_from_db,
)
from .state_manager import (
    init_session_state,
    require_cv_profile,
    get_user_profile,
    set_user_profile,
    get_temp_draft_profile,
    set_temp_draft_profile,
    get_raw_pdf_text,
    set_raw_pdf_text,
    get_parse_status,
    set_parse_status,
    set_demo_mode,
    reset_session,
    get_auth_user,
    is_user_logged_in,
    set_auth_user,
    clear_auth_user,
    render_auth_sidebar,
    DEMO_PROFILE_DATA,
)
from .cv_parser import (
    parse_cv,
    parse_cv_from_text,
    extract_raw_text_from_pdf,
    get_gemini_api_key,
    MAX_FILE_SIZE_MB,
    MAX_FILE_SIZE_BYTES,
    DEFAULT_MODEL,
)

__all__ = [
    "UserProfile",
    "Experience",
    "Education",
    "Project",
    "SkillNormalizer",
    "normalize_skills",
    "is_supabase_configured",
    "get_supabase_client",
    "sign_in_user",
    "sign_up_user",
    "sign_out_user",
    "save_profile_to_db",
    "load_profile_from_db",
    "init_session_state",
    "require_cv_profile",
    "get_user_profile",
    "set_user_profile",
    "get_temp_draft_profile",
    "set_temp_draft_profile",
    "get_raw_pdf_text",
    "set_raw_pdf_text",
    "get_parse_status",
    "set_parse_status",
    "set_demo_mode",
    "reset_session",
    "get_auth_user",
    "is_user_logged_in",
    "set_auth_user",
    "clear_auth_user",
    "render_auth_sidebar",
    "DEMO_PROFILE_DATA",
    "parse_cv",
    "parse_cv_from_text",
    "extract_raw_text_from_pdf",
    "get_gemini_api_key",
    "MAX_FILE_SIZE_MB",
    "MAX_FILE_SIZE_BYTES",
    "DEFAULT_MODEL",
]
